_target_: functional_diffusion_processes.samplers.ode_sampler.ODESampler
sampler_config:
  T: 1.0
  eps: 1e-3
  N: 100
  k: 1
  denoise: True
  output_size: ${datasets.train.data_config.output_size}
  do_super_resolution: False
