_target_: functional_diffusion_processes.samplers.pc_inpainter.PCInpainter
sampler_config:
  T: 1.0
  eps: 1e-3
  N: 100
  k: 1
  denoise: True
  output_size: ${datasets.train.data_config.output_size}
  task: ${trainers.training_config.sampling_type}
  do_super_resolution: False
