# @package _global_
defaults:
  - override /trainers: trainer_maml
  - override /models: mlp_modulation
  - override /datasets: mnist
  - override /samplers: ode_sampler
  - override /losses: ode_mse_loss
  - override /sdes: ode

trainers:
  model_name: "1200001_3fl5t8y4:v0"
  training_config:
    total_steps: 1600000
    eval_freq: 2000
    scheduler_steps: 10000
    checkpoint_freq: 2000
    resume_training: True
    warmup_steps: 6000
    decay_steps : 30000
    learning_rate: 1e-6
    peak_value: 3.3e-6
    end_value: 1e-6
    inner_learning_rate: 4e-3
    inner_steps: 3
    save_dir: ${oc.env:LOGS_ROOT}/train_inr_mnist_tune_trueRF_weightedpsm_corrected2
    use_meta_sgd: False
    ema_rate: 0.9999
    sampling_only: False
    weight_decay: 1e-6
  trainer_logging:
    use_wandb: True
    wandb_init:
      name: ${trainers.training_config.save_dir}
      project: "frf_tune_inr_mnist"

losses:
  loss_config:
    outer_psm: True
    frequency_space: True
    outer_fftshift: False
    normalize_time: True
    scheduler_steps: ${trainers.training_config.scheduler_steps}
    use_scheduler: False
    reduce_mean: False
    y_input: False


sdes:
  sde_config:
    psm_choice: "/nfs/turbo/coe-clayscot/jianxinz/fdp_project/data_stats/mnist_recip_std.npy"
    beta_max: 5.0
    const: 0.02
    psm_type: "time_independent"
    x_norm: 32
    energy_norm: 1

correctors:
  snr: 0.16

samplers:
  sampler_config:
    eps: 0.001
    N: 100
    k: 1
    denoise: True
    probability_flow: True
    factor: 0.6

models:
  model_config:
    use_dense_lr: False
    inner_fftshift: False
    layer_sizes:
      - 128
      - 128
      - 128
      - 128
      - 128
      - 128
      - 128
      - 128
      - ${datasets.train.data_config.output_size}
    y_input: False
datasets:
  train:
    data_config:
      batch_size: 32 #put the largest possible batch size
